Update file names to snake case and various minor fixes
TASLabz/mkw-scripts pull request #45
Opened 2023-10-22 06:47 UTC by kierio04

Review should check if all imports have been accounted for. A good majority of code ported from LUA core is still in camel case, however that's beyond the scope of this PR (and would require a good deal more work).

2023-10-22 06:51 UTC, malleoz commented on scripts/Modules/TTK_Lib.py
> +from . import ttk_config
If you're going to change capitalization here, you should rename the file too.

2023-10-22 06:51 UTC, malleoz commented on scripts/Modules/TTK_Lib.py
> +from . import ttk_config
This might requite a `git mv`

2023-10-22 06:51 UTC, malleoz commented on scripts/RMC/save_ghost_to_both_csv.py
> +from Modules import ttk_lib
Same as earlier comment

2023-10-22 07:08 UTC, vabold commented on scripts/Modules/mkw_utils.py
> +def get_igt(lap, player):
If we are going to enforce the snake case function rule, it should be done repository-wide in this PR.

2023-10-27 14:30 UTC, ximk requested changes
Consistency issues.

2023-10-27 14:30 UTC, ximk commented on scripts/RMC/Wheelie_Turn_Left.py
Why is this file being left capitalized?

2023-10-27 14:30 UTC, ximk commented on scripts/RMC/Wheelie_Turn_Right.py
see comments from wheelie_turn_left

2023-10-27 14:30 UTC, ximk commented on scripts/Modules/TTK_config.py
see @malleoz's comment on TTK_Lib

2023-10-28 05:40 UTC, kierio04 commented
Addressed all changes requested, so should be good to merge now.

2023-10-28 12:30 UTC, ximk approved these changes

2023-10-29 00:55 UTC, ximk requested changes
Will reapprove when fixes are made by myself.

2023-10-29 01:29 UTC, ximk approved these changes
Scripts should work fine now.

2023-10-29 01:33 UTC, malleoz submitted a review, later dismissed

2023-10-29 02:05 UTC, malleoz approved these changes
Tested and all scripts working on my end.

2023-10-29 02:05 UTC, merged